In [ ]:
import numpy as np #importing the numpy module to perform mathematical operations
import matplotlib.pyplot as plt #importing the matplotlib.pyplot module for picturising histograms
import pandas as pd #importing the pandas module to analyse and understand data

In [ ]:
data = pd.read_csv(('/content/Data.csv')) #using pd.read_csv to read and access the data from the dataset

In [ ]:
data.head() #this method returns columns and details of the first 5 rows by default, beginning from the top

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

data.iloc[] method is used to seperate columns and acces pandas data frame

In [ ]:
x = data.iloc[:,:-1].values
#using the index location method of the data and printing the values of all the columns except the last column

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
y = data.iloc[:,-1]
#using the index location of the data and printing everything other than the last column

In [ ]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


MISSING DATA

In [ ]:
from sklearn.impute import SimpleImputer
#importing the SimpleImputer class from the sklearn module to fill in the null or missing values

In [ ]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
#filling the missing values of the dataset with the mean strategy

In [ ]:
imputer.fit(x[:,1:3])
#using imputer.fit() filling all the empty, null values
#the 1:3 represents columnss 1 and 2, i.e., end - 1 column

SimpleImputer()

In [ ]:
x[:,1:3] = imputer.transform(x[:,1:3])
#using this method we replace missing values of the x column with a suitable value (mean of x column)

In [ ]:
x #calling x and checking if all the missing values have been filled

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

ENCODING CATEGORICAL DATA

In [ ]:
from sklearn.compose import ColumnTransformer
#importing the ColumnTransformer class frpm the sklearn.compose module to transform multiple columns simultaneously
from sklearn.preprocessing import OneHotEncoder
#importing the OneHotEncoder class from the sklearn.preprocessing module to convert categorical data to numerical data,
#by splitting a column into multiple columns

In [ ]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#using ColumnTransformer to transform columns with categorical data into numerical data

In [ ]:
x = np.array(ct.fit_transform(x)) #using this method we can fit and replacethe numerical values for the categorical data

In [ ]:
x #now printing the numerical data of the column that contained categorical data

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder #importing the LabelEncoder class from the sklearn.preprocessing module

In [ ]:
le = LabelEncoder() #using this method and convertig the categorical data into numerical values

In [ ]:
y = le.fit_transform(y) #label encoding the y column

In [ ]:
print(y) #printing the values of the y column in numerical form

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
#importing the train_test_split class from the sklearn.model_selection module

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
#using train_test_split and seperating the data of the dataset into test set and train set

In [ ]:
print(x_train) #printing the train set of x

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test) #printing the test set of x

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train) #printing the train set of y

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test) #printing the test set of y

[0 1]
